name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir 0build && cd 0build && cmake ..
    - name: make
      run: cd 0build && make
    - name: run tests
      run: cd 0build && ctest
